name: MDCHeroes
version: @version@-@apiversion@
description: MDCHeroes
authors: [ DartPower, BLitZzMc ]
website: https://github.com/dptmc/MDCHeroes
main: io.dpteam.MDCHeroes.Main
commands:
   heroes:
   dc:
   marvel: